version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app.docker
    image: chatss:app
    command: nodemon server.js
    container_name: chatss-app
    volumes:
      - ..:/app
    ports:
      - "8003:80"